"""Add sort_categories_by_usage to trips table

Revision ID: 6df1d7c20281
Revises: a3f8c1b2d4e6
Create Date: 2025-11-29 10:25:46.018654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6df1d7c20281'
down_revision: Union[str, None] = 'a3f8c1b2d4e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('sort_categories_by_usage', sa.Boolean(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'sort_categories_by_usage')
    # ### end Alembic commands ###
