"""Add display_order column to categories table

Revision ID: d66c97c5fdc5
Revises: 5611000e155c
Create Date: 2025-11-15 22:36:13.243353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd66c97c5fdc5'
down_revision: Union[str, None] = '5611000e155c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column with default value 0 for existing rows
    op.add_column('categories', sa.Column('display_order', sa.Integer(), nullable=False, server_default='0'))

    # Update existing categories to have sequential display_order based on their ID
    # This ensures existing categories maintain a consistent order
    connection = op.get_bind()
    connection.execute(sa.text("""
        UPDATE categories
        SET display_order = (
            SELECT COUNT(*)
            FROM categories c2
            WHERE c2.trip_id = categories.trip_id
            AND c2.id <= categories.id
        ) - 1
    """))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'display_order')
    # ### end Alembic commands ###
